Traceback (most recent call last):
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from importlib import reload

import sys
import os
import numpy as np
import xarray as xr

from copy import deepcopy

from scipy.ndimage import gaussian_filter

from matplotlib import pylab as plt
import cmocean
import json
import cartopy.crs as ccrs

# local modules contain software code that implement the SIC algorithm
from sirrdp import rrdp_file
from pmr_sic import tiepoints as tp
from pmr_sic import algo as sic_algo
from pmr_sic import hybrid_algo
from pmr_sic import common

# prototype re-gridding toolbox to handle the L1B input
if '/Tools/' not in sys.path:
    sys.path.insert(0, os.path.abspath('../..') + '/Tools/')
from tools import io_handler as io
from tools import collocation as coll
from tools import l2_format as l2

# top-level configuration for all plots
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 10})
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 18[0m
[1;32m     15[0m [38;5;28;01mimport[39;00m [38;5;21;01mcartopy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcrs[39;00m [38;5;28;01mas[39;00m [38;5;21;01mccrs[39;00m
[1;32m     17[0m [38;5;66;03m# local modules contain software code that implement the SIC algorithm[39;00m
[0;32m---> 18[0m [38;5;28;01mfrom[39;00m [38;5;21;01msirrdp[39;00m [38;5;28;01mimport[39;00m rrdp_file
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpmr_sic[39;00m [38;5;28;01mimport[39;00m tiepoints [38;5;28;01mas[39;00m tp
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpmr_sic[39;00m [38;5;28;01mimport[39;00m algo [38;5;28;01mas[39;00m sic_algo

[0;31mModuleNotFoundError[0m: No module named 'sirrdp'

